server:
  port: 8081
spring:
  datasource:
    password: root
    username: root
    url: jdbc:mysql://192.168.146.110:3306/gulimall_sms
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis-plus:
  mapper-locations: classpath:*/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
